# Models configuration for bizCon benchmark
# This file defines the models to be included in benchmark evaluations

models:
  - provider: D:/desktop/1/work/ai4c/benchmark/Qwen3-0.6B
    name: D:/desktop/1/work/ai4c/benchmark/Qwen3-0.6B
    temperature: 0.7
    max_tokens: 2048
    parameters:
      seed: 42